### PR TITLE
Fix authorization in the packaged app

### LINKED ISSUE #230: Make auth functional in packaged app

### PR DESCRIPTION
**Pull request by karczewskiPiotr**
## Description

⚠️ In order for the auth to work the callback url on github needs to be set to `publab://auth/callback`.

- Authorization in the packaged app is now working, 
- Environmental variables are properly loaded in the packaged app.

## Linked issues

Closes #230

### CODE REVIEW

File: src/main/index.ts [hunk 1]
```diff
@@ -1,25 +1,33 @@
...
+let mainWindow: InstanceType<typeof BrowserWindow>;
+const gotTheLock = app.requestSingleInstanceLock();
 
-export const mainStore = configStore('main');
+// Handle creating/removing shortcuts on Windows when installing/uninstalling.
+if (require('electron-squirrel-startup')) app.quit();
 
-registerApiHandlers();
+if (process.defaultApp) {
+  if (process.argv.length >= 2) {
```
Comment (LostInStatic) [inline src/main/index.ts:19]: This bit confuses me - I don't doubt the correctness, but I am not sure what is the case it covers. Could you add a comment?

Comment (LostInStatic) [inline src/main/index.ts:19]: This bit confuses me - I don't doubt the correctness, but I am not sure what is the case it covers. Could you add a comment?

**Review by LostInStatic — CHANGES_REQUESTED** [review]

File: src/main/index.ts (hunk 1 above)
Comment (karczewskiPiotr) [reply src/main/index.ts:23]: @LostInStatic added a bit of an explanation and link to docs but it is not exactly clear what passing the current js path does for the protocol set-up. I assume it's for opening links when app is running so it point to the currently running one instead of setting up a new one or something like that.

**Review by LostInStatic — APPROVED** [review]
